server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: 123456
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc.batch_size: 10000
        order_inserts: true
        order_updates: true
jwt:
  signerKey: "6092916c40862985551d0bc3e27ac332f9a824afe36ca89c418f0de63fe359f1"
  valid-duration: 30 # second
  refreshable-duration: 120 # second for test